apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: plex-auto-languages
    namespace: plex-auto-languages
spec:
    interval: 15m
    chart:
        spec:
            chart: plex-auto-languages
            version: 11.10.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: plex-auto-languages
    values:
        credentials:
            aws:
                type: s3
                accessKey: ${AWS_ACCESS_KEY}
                bucket: ${AWS_BUCKET}
                encrKey: ${AWS_ENCR_KEY}
                secretKey: ${AWS_SECRET_KEY}
                url: ${AWS_URL}
        persistence:
            config:
                volsync:
                    - credentials: aws
                      dest:
                        enabled: true
                      name: pal-config
                      src:
                        enabled: true
                      type: restic
        release_name: plex-auto-languages
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                PLEX_TOKEN: ${PLEX_AUTO_LANGUAGE_TOKEN}
                                PLEX_URL: ${PLEX_AUTO_LANGUAGE_URL}
