apiVersion: v1
kind: Pod
metadata:
  name: cleanup-pod
  namespace: qbittorrent
spec:
  containers:
  - name: sqlite
    image: alpine:latest
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: "/mnt/data"
      name: postgres-storage
  volumes:
  - name: postgres-storage
    persistentVolumeClaim:
      claimName: qbittorrent-config
  restartPolicy: Never
