apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: mosquitto
    namespace: mosquitto
spec:
    interval: 15m
    chart:
        spec:
            chart: mosquitto
            version: 17.8.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: mosquitto
    values:
        TZ: Europe/Berlin
        credentials:
            aws:
                type: s3
                accessKey: ${AWS_ACCESS_KEY}
                bucket: ${AWS_BUCKET}
                encrKey: ${AWS_ENCR_KEY}
                secretKey: ${AWS_SECRET_KEY}
                url: ${AWS_URL}
        persistence:
            configinc:
                volsync:
                    - credentials: aws
                      name: mosquitto-config
                      src:
                          enabled: true
                      dest:
                          enabled: true
                      type: restic
            data:
                volsync:
                    - credentials: aws
                      name: mosquitto-data
                      src:
                          enabled: true
                      dest:
                          enabled: true
                      type: restic
        release_name: mosquitto
        service:
            main:
                type: LoadBalancer
                integrations:
                    metallb:
                        enabled: true
            websockets:
                type: ClusterIP
