apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: flaresolverr
    namespace: flaresolverr
spec:
    interval: 15m
    chart:
        spec:
            chart: flaresolverr
            version: 15.5.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: flaresolverr
    values:
        TZ: Europe/Berlin
        credentials:
            aws:
                type: s3
                accessKey: ${AWS_ACCESS_KEY}
                bucket: ${AWS_BUCKET}
                encrKey: ${AWS_ENCR_KEY}
                secretKey: ${AWS_SECRET_KEY}
                url: ${AWS_URL}
        persistence:
            config:
                volsync:
                    - credentials: aws
                      dest:
                        enabled: true
                      name: flaresolverr-config
                      src:
                        enabled: true
                      type: restic
        release_name: flaresolverr
