apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: requestrr
    namespace: requestrr
spec:
    interval: 15m
    chart:
        spec:
            chart: requestrr
            version: 13.10.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: requestrr
    values:
        TZ: Europe/Berlin
        credentials:
            aws:
                type: s3
                accessKey: ${AWS_ACCESS_KEY}
                bucket: ${AWS_BUCKET}
                encrKey: ${AWS_ENCR_KEY}
                secretKey: ${AWS_SECRET_KEY}
                url: ${AWS_URL}
        persistence:
            config:
                volsync:
                    - credentials: aws
                      name: requestrr-config
                      src:
                          enabled: true
                      dest:
                          enabled: true
                      type: restic
        release_name: requestrr
        ingress:
            main:
                enabled: true
                ingressClassName: internal
                integrations:
                    traefik:
                        enabled: false
                    certManager:
                        enabled: true
                        certificateIssuer: domain-0-le-prod
                hosts:
                    - host: requestrr.${DOMAIN_0}
                      paths:
                          - path: /
                            pathType: Prefix
