apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: homepage
    namespace: homepage
spec:
    interval: 15m
    chart:
        spec:
            chart: homepage
            version: 11.4.6
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: homepage
    values:
        TZ: Europe/Berlin
        credentials:
            aws:
                type: s3
                accessKey: ${AWS_ACCESS_KEY}
                bucket: ${AWS_BUCKET}
                encrKey: ${AWS_ENCR_KEY}
                secretKey: ${AWS_SECRET_KEY}
                url: ${AWS_URL}
        persistence:
            config:
                volsync:
                    - credentials: aws
                      name: homepage-config
                      src:
                          enabled: true
                      dest:
                          enabled: true
                      type: restic
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                # Set this to your host (example: home.mydomain.com)
                                HOMEPAGE_ALLOWED_HOSTS: "home.${DOMAIN_0}"
        release_name: homepage
        ingress:
            main:
                enabled: true
                ingressClassName: internal
                integrations:
                    traefik:
                        enabled: false
                    certManager:
                        enabled: true
                        certificateIssuer: domain-0-le-prod
                hosts:
                    - host: home.${DOMAIN_0}
                      paths:
                          - path: /
                            pathType: Prefix
        addons:
            codeserver:
                enabled: true
                ingress:
                    enabled: true
                    integrations:
                        traefik:
                            enabled: false
                        certManager:
                            enabled: true
                            certificateIssuer: domain-0-le-prod
                    hosts:
                        - host: home-edit.${DOMAIN_0}
                          paths:
                              - path: /
                                pathType: Prefix
                service:
                    ports:
                        codeserver:
                            port: 36107
        resources:
            requests: # TEMP UNTIL CPU UPGRADE
                pu: 50m
