apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: plex
    namespace: plex
spec:
    interval: 15m
    chart:
        spec:
            chart: plex
            version: 19.6.11
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: plex
    values:
        TZ: Europe/Berlin
        credentials:
            aws:
                type: s3
                accessKey: ${AWS_ACCESS_KEY}
                bucket: ${AWS_BUCKET}
                encrKey: ${AWS_ENCR_KEY}
                secretKey: ${AWS_SECRET_KEY}
                url: ${AWS_URL}
#        ingress:
#            main:
#                enabled: true
#                hosts:
#                    - host: plex.k0nr4d.de
#                      paths:
#                        - path: /
#                          pathType: Prefix
#                integrations:
#                    certManager:
#                        certificateIssuer: maincert
#                        enabled: true
#                    traefik:
#                        allowCors: false
#                        enabled: true
#                        entrypoints:
#                            - websecure
        persistence:
            config:
                volsync:
                    - credentials: aws
                      name: plex-config
                      src:
                          enabled: true
                      dest:
                          enabled: true
                      type: restic
            data-vol:
                enabled: true
                type: nfs
                mountPath: /data/media
                path: /mnt/Helios/data/media
                server: ${LOCAL_NAS_IP}
        securityContext:
            container:
                UMASK: "0022"
                runAsGroup: 568
                runAsUser: 568
            pod:
                fsGroupChangePolicy: OnRootMismatch
        plex:
            additionalAdvertiseURL: ""
            disableGDM: true
            requireHTTPS: false
            serverIP: 10.0.0.223
        release_name: plex
        service:
            main:
                type: LoadBalancer
#        workload:
#            main:
#                podSpec:
#                    containers:
#                        main:
#                            env:
#                                PLEX_CLAIM: ${PLEX_CLAIM}
