apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - volumeSnapshotClass.yaml
  - cron-filesystem-trim.yaml
  - cron-snapshot-cleanup.yaml
  - cron-snapshot-delete.yaml
  - ingress.yaml
