apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: home-assistant
    namespace: home-assistant
spec:
    interval: 15m
    chart:
        spec:
            chart: home-assistant
            version: 28.10.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: home-assistant
    values:
        TZ: Europe/Berlin
        addons:
            codeserver:
                enabled: true
                service:
                    ports:
                        codeserver:
                            port: 36107
                    type: LoadBalancer
                integrations:
                    metallb:
                        enabled: true
        cnpg:
            main:
                backups:
                    credentials: aws
                    enabled: true
                    retentionPolicy: "14d"
                    revision: "1"
                cluster:
                    singleNode: true
                database: home-assistant
                mode: recovery
                password: ${HOME_ASSISTANT_DB_PW}
                recovery:
                    credentials: aws
                    enabled: true
                    revision: ""
        credentials:
            aws:
                type: s3
                accessKey: ${AWS_ACCESS_KEY}
                bucket: ${AWS_BUCKET}
                encrKey: ${AWS_ENCR_KEY}
                secretKey: ${AWS_SECRET_KEY}
                url: ${AWS_URL}
        persistence:
            config:
                volsync:
                    - credentials: aws
                      type: restic
                      name: home-assistant-config
                      src:
                          enabled: true
                      dest:
                          enabled: true
            skyconnect:
                enabled: true
                type: device
                hostPath: /dev/ttyUSB0
        release_name: home-assistant
        #        service:
        #            main:
        #                type: LoadBalancer
        ingress:
            main:
                enabled: true
                ingressClassName: internal
                integrations:
                    traefik:
                        enabled: false
                    certManager:
                        enabled: true
                        certificateIssuer: domain-0-le-prod
                hosts:
                    - host: ha.${DOMAIN_0}
                      paths:
                          - path: /
                            pathType: Prefix
        resources:
            requests: # TEMP UNTIL CPU UPGRADE
                pu: 100m
