apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: external-proxmox
    namespace: external-proxmox
spec:
    interval: 15m
    chart:
        spec:
            chart: external-service
            version: 15.6.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: external-proxmox
    values:
        TZ: Europe/Berlin
        release_name: external-proxmox
        ingress:
            main:
                type: ExternalIP
                externalIP: ${EXTERNAL_PROXMOX}
                useSlice: false
                ports:
                  main:
                    protocol: https
                    port: 8006
                enabled: true
                ingressClassName: internal
                integrations:
                    traefik:
                        enabled: false
                    certManager:
                        enabled: true
                        certificateIssuer: domain-0-le-prod
                hosts:
                    - host: prox.${DOMAIN_0}
                      paths:
                          - path: /
                            pathType: Prefix
